/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package finalnatalagathisasin;

import java.awt.Font;
import java.awt.GridLayout;
import java.text.DecimalFormat;
import javax.swing.JLabel;
import javax.swing.JTextField;
import java.util.List;
import java.util.ArrayList;

/**
 *
 * @author rexiepimentelMBP
 */
public class Main extends javax.swing.JFrame {

    /**
     * Creates new form Main
     */
    private List<JTextField> textFields = new ArrayList<>();
    int givenFields;
    private List<String> variableNames = new ArrayList<>();
    
    Font defaultFont = new Font("Helvetica Neue", Font.PLAIN, 36);
    
    DecimalFormat decimalFormat = new DecimalFormat("#.00");
    
    ShapesFormula sf = new ShapesFormula();
    
    public Main() {
        initComponents();
        
    }
    public void textFieldsHandler(){
        
        panelTextFields.removeAll();
        panelTextFields.setLayout(new GridLayout(0, 2));
        textFields.clear();
        
        
        int count;
        int givenFieldCount = givenFields;

        for (int i = 0; i < givenFieldCount; i++) {
            String varNames = variableNames.get(i);
            
            JLabel label = new JLabel(varNames + ": ");
            label.setFont(defaultFont);
            panelTextFields.add(label);
            
            JTextField field  = new JTextField(10);
            field.setFont(defaultFont);
            panelTextFields.add(field);
            textFields.add(field);
        }

        panelTextFields.revalidate();
        panelTextFields.repaint();
    }
    
    public void clearAnswer(){
        lblAnswer.setText("Selected Shape Answer");
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainPanel = new javax.swing.JPanel();
        panelTitle = new javax.swing.JPanel();
        panelShapeName = new javax.swing.JPanel();
        lblSelectedShapeName = new javax.swing.JLabel();
        panelSelectedShapeFormula = new javax.swing.JPanel();
        lblSelectedShapeFormula = new javax.swing.JLabel();
        panelShapeDiagram = new javax.swing.JPanel();
        panelSelectedShapeAnswer = new javax.swing.JPanel();
        lblAnswer = new javax.swing.JLabel();
        panelSelectedShapeInputs = new javax.swing.JPanel();
        panelTextFields = new javax.swing.JPanel();
        btnCalculate = new javax.swing.JButton();
        btnClear = new javax.swing.JButton();
        tabbedPaneShapeSelection = new javax.swing.JTabbedPane();
        scrollPane2dShapes = new javax.swing.JScrollPane();
        panel2dShapes = new javax.swing.JPanel();
        btnCircle = new javax.swing.JButton();
        btnEllipse = new javax.swing.JButton();
        btnTriangle = new javax.swing.JButton();
        btnRectangle = new javax.swing.JButton();
        btnSquare = new javax.swing.JButton();
        btnParallelogram = new javax.swing.JButton();
        btnPentagon = new javax.swing.JButton();
        btnHexagon = new javax.swing.JButton();
        btnHeptagon = new javax.swing.JButton();
        btnOctagon = new javax.swing.JButton();
        btnNonagon = new javax.swing.JButton();
        btnDecagon = new javax.swing.JButton();
        btnRhombus = new javax.swing.JButton();
        btnTrapezoid = new javax.swing.JButton();
        scrollPane3dShapes = new javax.swing.JScrollPane();
        panel3dShapes = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        mainPanel.setLayout(null);

        panelTitle.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        javax.swing.GroupLayout panelTitleLayout = new javax.swing.GroupLayout(panelTitle);
        panelTitle.setLayout(panelTitleLayout);
        panelTitleLayout.setHorizontalGroup(
            panelTitleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 218, Short.MAX_VALUE)
        );
        panelTitleLayout.setVerticalGroup(
            panelTitleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 148, Short.MAX_VALUE)
        );

        mainPanel.add(panelTitle);
        panelTitle.setBounds(0, 0, 220, 150);

        panelShapeName.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        panelShapeName.setLayout(null);

        lblSelectedShapeName.setFont(new java.awt.Font("Helvetica Neue", 0, 24)); // NOI18N
        lblSelectedShapeName.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblSelectedShapeName.setText("Selected Shape Name");
        panelShapeName.add(lblSelectedShapeName);
        lblSelectedShapeName.setBounds(6, 21, 1048, 29);

        mainPanel.add(panelShapeName);
        panelShapeName.setBounds(220, 0, 1060, 60);

        panelSelectedShapeFormula.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        panelSelectedShapeFormula.setLayout(null);

        lblSelectedShapeFormula.setFont(new java.awt.Font("Helvetica Neue", 0, 24)); // NOI18N
        lblSelectedShapeFormula.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblSelectedShapeFormula.setText("Selected Shape Formula");
        panelSelectedShapeFormula.add(lblSelectedShapeFormula);
        lblSelectedShapeFormula.setBounds(0, -1, 1060, 110);

        mainPanel.add(panelSelectedShapeFormula);
        panelSelectedShapeFormula.setBounds(220, 610, 1060, 110);

        panelShapeDiagram.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        javax.swing.GroupLayout panelShapeDiagramLayout = new javax.swing.GroupLayout(panelShapeDiagram);
        panelShapeDiagram.setLayout(panelShapeDiagramLayout);
        panelShapeDiagramLayout.setHorizontalGroup(
            panelShapeDiagramLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 288, Short.MAX_VALUE)
        );
        panelShapeDiagramLayout.setVerticalGroup(
            panelShapeDiagramLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 548, Short.MAX_VALUE)
        );

        mainPanel.add(panelShapeDiagram);
        panelShapeDiagram.setBounds(220, 60, 290, 550);

        panelSelectedShapeAnswer.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        lblAnswer.setFont(new java.awt.Font("Helvetica Neue", 0, 24)); // NOI18N
        lblAnswer.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblAnswer.setText("Selected Shape Answer");

        javax.swing.GroupLayout panelSelectedShapeAnswerLayout = new javax.swing.GroupLayout(panelSelectedShapeAnswer);
        panelSelectedShapeAnswer.setLayout(panelSelectedShapeAnswerLayout);
        panelSelectedShapeAnswerLayout.setHorizontalGroup(
            panelSelectedShapeAnswerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelSelectedShapeAnswerLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblAnswer, javax.swing.GroupLayout.DEFAULT_SIZE, 756, Short.MAX_VALUE)
                .addContainerGap())
        );
        panelSelectedShapeAnswerLayout.setVerticalGroup(
            panelSelectedShapeAnswerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelSelectedShapeAnswerLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblAnswer, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        mainPanel.add(panelSelectedShapeAnswer);
        panelSelectedShapeAnswer.setBounds(510, 350, 770, 260);

        panelSelectedShapeInputs.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        panelTextFields.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        panelTextFields.setLayout(new java.awt.GridLayout(1, 0));

        btnCalculate.setText("Calculate");
        btnCalculate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCalculateActionPerformed(evt);
            }
        });

        btnClear.setText("Clear");
        btnClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClearActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelSelectedShapeInputsLayout = new javax.swing.GroupLayout(panelSelectedShapeInputs);
        panelSelectedShapeInputs.setLayout(panelSelectedShapeInputsLayout);
        panelSelectedShapeInputsLayout.setHorizontalGroup(
            panelSelectedShapeInputsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelSelectedShapeInputsLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelTextFields, javax.swing.GroupLayout.PREFERRED_SIZE, 567, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelSelectedShapeInputsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnCalculate, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnClear, javax.swing.GroupLayout.DEFAULT_SIZE, 177, Short.MAX_VALUE))
                .addContainerGap())
        );
        panelSelectedShapeInputsLayout.setVerticalGroup(
            panelSelectedShapeInputsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelSelectedShapeInputsLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(panelSelectedShapeInputsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelSelectedShapeInputsLayout.createSequentialGroup()
                        .addComponent(btnCalculate, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnClear, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(panelTextFields, javax.swing.GroupLayout.PREFERRED_SIZE, 258, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(15, Short.MAX_VALUE))
        );

        mainPanel.add(panelSelectedShapeInputs);
        panelSelectedShapeInputs.setBounds(510, 60, 770, 290);

        btnCircle.setText("Circle");
        btnCircle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCircleActionPerformed(evt);
            }
        });

        btnEllipse.setText("Ellipse");
        btnEllipse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEllipseActionPerformed(evt);
            }
        });

        btnTriangle.setText("Triangle");
        btnTriangle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTriangleActionPerformed(evt);
            }
        });

        btnRectangle.setText("Rectangle");
        btnRectangle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRectangleActionPerformed(evt);
            }
        });

        btnSquare.setText("Square");
        btnSquare.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSquareActionPerformed(evt);
            }
        });

        btnParallelogram.setText("Parallelogram");
        btnParallelogram.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnParallelogramActionPerformed(evt);
            }
        });

        btnPentagon.setText("Pentagon");
        btnPentagon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPentagonActionPerformed(evt);
            }
        });

        btnHexagon.setText("Hexagon");
        btnHexagon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHexagonActionPerformed(evt);
            }
        });

        btnHeptagon.setText("Heptagon");
        btnHeptagon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHeptagonActionPerformed(evt);
            }
        });

        btnOctagon.setText("Octagon");
        btnOctagon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOctagonActionPerformed(evt);
            }
        });

        btnNonagon.setText("Nonagon");
        btnNonagon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNonagonActionPerformed(evt);
            }
        });

        btnDecagon.setText("Decagon");
        btnDecagon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDecagonActionPerformed(evt);
            }
        });

        btnRhombus.setText("Rhombus");
        btnRhombus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRhombusActionPerformed(evt);
            }
        });

        btnTrapezoid.setText("Trapezoid");
        btnTrapezoid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTrapezoidActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panel2dShapesLayout = new javax.swing.GroupLayout(panel2dShapes);
        panel2dShapes.setLayout(panel2dShapesLayout);
        panel2dShapesLayout.setHorizontalGroup(
            panel2dShapesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel2dShapesLayout.createSequentialGroup()
                .addGroup(panel2dShapesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panel2dShapesLayout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(btnCircle, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panel2dShapesLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btnEllipse, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panel2dShapesLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btnTriangle, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panel2dShapesLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btnRectangle, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panel2dShapesLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btnSquare, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panel2dShapesLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btnParallelogram, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panel2dShapesLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btnPentagon, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panel2dShapesLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btnHexagon, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panel2dShapesLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btnHeptagon, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panel2dShapesLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btnOctagon, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panel2dShapesLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btnNonagon, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panel2dShapesLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btnDecagon, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panel2dShapesLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btnRhombus, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panel2dShapesLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btnTrapezoid, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(22, 22, 22))
        );
        panel2dShapesLayout.setVerticalGroup(
            panel2dShapesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel2dShapesLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnCircle, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnEllipse, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnTriangle, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnSquare, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnRectangle, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnParallelogram, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnPentagon, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnHexagon, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnHeptagon, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnOctagon, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnNonagon, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnDecagon, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnRhombus, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnTrapezoid, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(70, Short.MAX_VALUE))
        );

        scrollPane2dShapes.setViewportView(panel2dShapes);

        tabbedPaneShapeSelection.addTab("2D Shapes", scrollPane2dShapes);

        javax.swing.GroupLayout panel3dShapesLayout = new javax.swing.GroupLayout(panel3dShapes);
        panel3dShapes.setLayout(panel3dShapesLayout);
        panel3dShapesLayout.setHorizontalGroup(
            panel3dShapesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 214, Short.MAX_VALUE)
        );
        panel3dShapesLayout.setVerticalGroup(
            panel3dShapesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 529, Short.MAX_VALUE)
        );

        scrollPane3dShapes.setViewportView(panel3dShapes);

        tabbedPaneShapeSelection.addTab("3D Shapes", scrollPane3dShapes);

        mainPanel.add(tabbedPaneShapeSelection);
        tabbedPaneShapeSelection.setBounds(0, 150, 220, 570);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 1280, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 720, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCircleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCircleActionPerformed
        // TODO add your handling code here:

        givenFields = 1;
        
        lblSelectedShapeName.setText("Circle");
        lblSelectedShapeFormula.setText(sf.circle());
        
        variableNames.clear();
        variableNames.add("radius");
        
        
        textFieldsHandler();
        clearAnswer();
        
    }//GEN-LAST:event_btnCircleActionPerformed

    private void btnEllipseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEllipseActionPerformed
        // TODO add your handling code here:
        
        givenFields = 2;
        
        lblSelectedShapeName.setText("Ellipse");
        lblSelectedShapeFormula.setText(sf.circle());
        
        variableNames.clear();
        variableNames.add("Given a");
        variableNames.add("Given b");
        
        textFieldsHandler();
        clearAnswer();
    }//GEN-LAST:event_btnEllipseActionPerformed

    private void btnTriangleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTriangleActionPerformed
        // TODO add your handling code here:
        
        givenFields = 3;
        
        lblSelectedShapeName.setText("Triangle");
        lblSelectedShapeFormula.setText(sf.triangle());
        
        variableNames.clear();
        variableNames.add("Given a");
        variableNames.add("Given b");
        variableNames.add("Given c");
        
        textFieldsHandler();
        clearAnswer();
    }//GEN-LAST:event_btnTriangleActionPerformed

    private void btnRectangleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRectangleActionPerformed
        // TODO add your handling code here:

        givenFields = 2;
        
        lblSelectedShapeName.setText("Rectangle");
        lblSelectedShapeFormula.setText(sf.rectangle());
        
        variableNames.clear();
        variableNames.add("Given length");
        variableNames.add("Given width");
        
        textFieldsHandler();
        clearAnswer();
    }//GEN-LAST:event_btnRectangleActionPerformed

    private void btnSquareActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSquareActionPerformed
        // TODO add your handling code here:

        givenFields = 1;
        
        lblSelectedShapeName.setText("Square");
        lblSelectedShapeFormula.setText(sf.square());
        
        variableNames.clear();
        variableNames.add("Given a");
        
        textFieldsHandler();
        clearAnswer();
    }//GEN-LAST:event_btnSquareActionPerformed

    private void btnParallelogramActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnParallelogramActionPerformed
        // TODO add your handling code here:
        
        givenFields = 3;
        
        lblSelectedShapeName.setText("Parallelogram");
        lblSelectedShapeFormula.setText(sf.parallelogram());
        
        variableNames.clear();
        variableNames.add("Given base");
        variableNames.add("Given side");
        variableNames.add("Given height");
        
        textFieldsHandler();
        clearAnswer();        
    }//GEN-LAST:event_btnParallelogramActionPerformed

    private void btnPentagonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPentagonActionPerformed
        // TODO add your handling code here:
        givenFields = 1;
        
        lblSelectedShapeName.setText("Pentagon");
        lblSelectedShapeFormula.setText(sf.pentagon());
        
        variableNames.clear();
        variableNames.add("Given side");
        
        textFieldsHandler();
        clearAnswer();                
    }//GEN-LAST:event_btnPentagonActionPerformed

    private void btnHexagonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHexagonActionPerformed
        // TODO add your handling code here:
        givenFields = 1;
        
        lblSelectedShapeName.setText("Hexagon");
        lblSelectedShapeFormula.setText(sf.hexagon());
        
        variableNames.clear();
        variableNames.add("Given side");
        
        textFieldsHandler();
        clearAnswer();           
    }//GEN-LAST:event_btnHexagonActionPerformed

    private void btnHeptagonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHeptagonActionPerformed
        // TODO add your handling code here:
        givenFields = 1;
        
        lblSelectedShapeName.setText("Heptagon");
        lblSelectedShapeFormula.setText(sf.heptagon());
        
        variableNames.clear();
        variableNames.add("Given side");
        
        textFieldsHandler();
        clearAnswer();           
    }//GEN-LAST:event_btnHeptagonActionPerformed

    private void btnOctagonActionPerformed(java.awt.event.ActionEvent evt) {                                           
        // TODO add your handling code here:
        givenFields = 1;
        
        lblSelectedShapeName.setText("Octagon");
        lblSelectedShapeFormula.setText(sf.octagon());
        
        variableNames.clear();
        variableNames.add("Given side");
        
        textFieldsHandler();
        clearAnswer();           
    }                      
    
    private void btnNonagonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNonagonActionPerformed
        // TODO add your handling code here:
        givenFields = 1;
        
        lblSelectedShapeName.setText("Nonagon");
        lblSelectedShapeFormula.setText(sf.nonagon());
        
        variableNames.clear();
        variableNames.add("Given side");
        
        textFieldsHandler();
        clearAnswer();             
    }//GEN-LAST:event_btnNonagonActionPerformed

    private void btnDecagonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDecagonActionPerformed
        // TODO add your handling code here:
        givenFields = 1;
        
        lblSelectedShapeName.setText("Decagon");
        lblSelectedShapeFormula.setText(sf.decagon());
        
        variableNames.clear();
        variableNames.add("Given side");
        
        textFieldsHandler();
        clearAnswer();
    }//GEN-LAST:event_btnDecagonActionPerformed

    private void btnRhombusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRhombusActionPerformed
        // TODO add your handling code here:
        givenFields = 3;
        
        lblSelectedShapeName.setText("Rhombus");
        lblSelectedShapeFormula.setText(sf.rhombus());
        
        variableNames.clear();
        variableNames.add("Given side");
        variableNames.add("Diagonal p");
        variableNames.add("Diagonal q");
        
        textFieldsHandler();
        clearAnswer();
    }//GEN-LAST:event_btnRhombusActionPerformed

    private void btnTrapezoidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTrapezoidActionPerformed
        // TODO add your handling code here:
        givenFields = 5;
        
        lblSelectedShapeName.setText("Trapezoid");
        lblSelectedShapeFormula.setText(sf.trapezoid());
        
        variableNames.clear();
        variableNames.add("side a");
        variableNames.add("side b");
        variableNames.add("base c");
        variableNames.add("base d");
        variableNames.add("height");
        
        textFieldsHandler();
        clearAnswer();        
    }//GEN-LAST:event_btnTrapezoidActionPerformed


    private void btnCalculateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCalculateActionPerformed
        // TODO add your handling code here:
        
        //Circle
        
        if ("Circle".equals(lblSelectedShapeName.getText())) {
            try {
                //For Rounding: https://stackoverflow.com/questions/2808535/round-a-double-to-2-decimal-places
                //For Double Handler: https://stackoverflow.com/questions/49466030/how-to-convert-double-values-to-string-in-a-text-field
                double radius = Double.parseDouble(textFields.get(0).getText());
                double diameter = radius * 2;
                double circumference = 2 * Math.PI * radius;
                double area = Math.PI * radius * radius;

                lblAnswer.setText("<html>Diameter = " + decimalFormat.format(diameter) +
                    "<br>Circumference = " + decimalFormat.format(circumference) +
                    "<br>Area = " + decimalFormat.format(area) + "</html>");
                } catch (NumberFormatException ex) {
                lblAnswer.setText("Invalid radius. Please enter a number.");
                }
            
        }
        
        //Ellipse
        
        else if ("Ellipse".equals(lblSelectedShapeName.getText())) {
            try {
                double a = Double.parseDouble(textFields.get(0).getText());
                double b = Double.parseDouble(textFields.get(1).getText());
                double area = Math.PI * a * b;
                double perimeter = 2 * Math.PI * Math.sqrt((a * a + b * b) / 2);

                lblAnswer.setText("<html>Perimeter = " + decimalFormat.format(perimeter) +
                "<br>Area = " + decimalFormat.format(area) + "</html>");
            } catch (NumberFormatException ex) {
                lblAnswer.setText("Invalid radius. Please enter a number.");
            }
        }
        
        //Triangle
        
        else if ("Triangle".equals(lblSelectedShapeName.getText())) {
            try {
                double a = Double.parseDouble(textFields.get(0).getText());
                double b = Double.parseDouble(textFields.get(1).getText());
                double c = Double.parseDouble(textFields.get(2).getText());
                
                double s = (a + b + c) / 2;
                double perimeter = a + b + c;
                double area = Math.sqrt(s * (s - a) * (s - b) * (s - c));

                lblAnswer.setText("<html>Perimeter = " + decimalFormat.format(perimeter) +
                "<br>Area = " + decimalFormat.format(area) + "</html>");
            } catch (NumberFormatException ex) {
                lblAnswer.setText("Invalid radius. Please enter a number.");
            }            
        }
        
        //Square
        
        else if ("Square".equals(lblSelectedShapeName.getText())) {
            try {
                double a = Double.parseDouble(textFields.get(0).getText());
                
                double perimeter = 4 * a;
                double area = Math.pow(a, 2);

                lblAnswer.setText("<html>Perimeter = " + decimalFormat.format(perimeter) +
                "<br>Area = " + decimalFormat.format(area) + "</html>");
            } catch (NumberFormatException ex) {
                lblAnswer.setText("Invalid radius. Please enter a number.");
            }
        }
        
        //Rectangle
        
        else if ("Rectangle".equals(lblSelectedShapeName.getText())) {
            try {
                double length = Double.parseDouble(textFields.get(0).getText());
                double width = Double.parseDouble(textFields.get(1).getText());
                
                double perimeter = 2 * (length + width);
                double area = length * width;

                lblAnswer.setText("<html>Perimeter = " + decimalFormat.format(perimeter) +
                "<br>Area = " + decimalFormat.format(area) + "</html>");
            } catch (NumberFormatException ex) {
                lblAnswer.setText("Invalid radius. Please enter a number.");
            }
        }
        
        //Parallelogram
        
        else if ("Parallelogram".equals(lblSelectedShapeName.getText())) {
            try {
                double base = Double.parseDouble(textFields.get(0).getText());
                double side = Double.parseDouble(textFields.get(1).getText());
                double height = Double.parseDouble(textFields.get(2).getText());
                
                
                double perimeter = 2 * (base + side);
                double area = base * height;

                lblAnswer.setText("<html>Perimeter = " + decimalFormat.format(perimeter) +
                "<br>Area = " + decimalFormat.format(area) + "</html>");
            } catch (NumberFormatException ex) {
                lblAnswer.setText("Invalid radius. Please enter a number.");
            } 
        }
        
        //Pentagon
        
        else if ("Pentagon".equals(lblSelectedShapeName.getText())) {
            try {
                double side = Double.parseDouble(textFields.get(0).getText());
                
                double perimeter = 5 * side;
                double area = (5 * Math.pow(side, 2)) / (4 * Math.tan(Math.PI/5));

                lblAnswer.setText("<html>Perimeter = " + decimalFormat.format(perimeter) +
                "<br>Area = " + decimalFormat.format(area) + "</html>");
            } catch (NumberFormatException ex) {
                lblAnswer.setText("Invalid radius. Please enter a number.");
            } 
        }
        
        //Hexagon
        
        else if ("Hexagon".equals(lblSelectedShapeName.getText())) {
            try {
                double side = Double.parseDouble(textFields.get(0).getText());
                
                
                double perimeter = 6 * side;
                double area = (3 * Math.sqrt(3) * Math.pow(side, 2) / 2);

                lblAnswer.setText("<html>Perimeter = " + decimalFormat.format(perimeter) +
                "<br>Area = " + decimalFormat.format(area) + "</html>");
            } catch (NumberFormatException ex) {
                lblAnswer.setText("Invalid radius. Please enter a number.");
            } 
        }
        
        //Heptagon
        
        else if ("Heptagon".equals(lblSelectedShapeName.getText())) {
            try {
                double side = Double.parseDouble(textFields.get(0).getText());
                
                
                double perimeter = 7 * side;
                double area = (7 * Math.pow(side, 2)) / (4 * Math.tan(Math.PI/7));

                lblAnswer.setText("<html>Perimeter = " + decimalFormat.format(perimeter) +
                "<br>Area = " + decimalFormat.format(area) + "</html>");
            } catch (NumberFormatException ex) {
                lblAnswer.setText("Invalid radius. Please enter a number.");
            } 
        }
        
        //Octagon
        
        else if ("Octagon".equals(lblSelectedShapeName.getText())) {
            try {
                double side = Double.parseDouble(textFields.get(0).getText());
                
                
                double perimeter = 8 * side;
                double area = 2 * (1 + Math.sqrt(2)) * Math.pow(side, 2);

                lblAnswer.setText("<html>Perimeter = " + decimalFormat.format(perimeter) +
                "<br>Area = " + decimalFormat.format(area) + "</html>");
            } catch (NumberFormatException ex) {
                lblAnswer.setText("Invalid radius. Please enter a number.");
            } 
        }
        
        //Nonagon
        
        else if ("Nonagon".equals(lblSelectedShapeName.getText())) {
            try {
                double side = Double.parseDouble(textFields.get(0).getText());
                
                
                double perimeter = 9 * side;
                double area = (9 * Math.pow(side, 2)) / (4 * Math.tan(Math.PI/9));

                lblAnswer.setText("<html>Perimeter = " + decimalFormat.format(perimeter) +
                "<br>Area = " + decimalFormat.format(area) + "</html>");
            } catch (NumberFormatException ex) {
                lblAnswer.setText("Invalid radius. Please enter a number.");
            } 
        }
        
        //Decagon
        
        else if ("Decagon".equals(lblSelectedShapeName.getText())) {
            try {
                double side = Double.parseDouble(textFields.get(0).getText());
                
                
                double perimeter = 10 * side;
                double area = (5 * Math.pow(side, 2)) / (2 * Math.tan(Math.PI/10));

                lblAnswer.setText("<html>Perimeter = " + decimalFormat.format(perimeter) +
                "<br>Area = " + decimalFormat.format(area) + "</html>");
            } catch (NumberFormatException ex) {
                lblAnswer.setText("Invalid radius. Please enter a number.");
            } 
        }
        
        //Rhombus
        
        else if ("Rhombus".equals(lblSelectedShapeName.getText())) {
            try {
                double side = Double.parseDouble(textFields.get(0).getText());
                double diagonalP = Double.parseDouble(textFields.get(1).getText());
                double diagonalQ = Double.parseDouble(textFields.get(2).getText());
                
                
                double perimeter = 4 * side;
                double area = (diagonalP * diagonalQ) / 2;

                lblAnswer.setText("<html>Perimeter = " + decimalFormat.format(perimeter) +
                "<br>Area = " + decimalFormat.format(area) + "</html>");
            } catch (NumberFormatException ex) {
                lblAnswer.setText("Invalid radius. Please enter a number.");
            } 
        }
        
        //Trapezoid
        
        else if ("Trapezoid".equals(lblSelectedShapeName.getText())) {
            try {
                double sideA = Double.parseDouble(textFields.get(0).getText());
                double sideB = Double.parseDouble(textFields.get(1).getText());
                double baseC = Double.parseDouble(textFields.get(2).getText());
                double baseD = Double.parseDouble(textFields.get(3).getText());
                double height = Double.parseDouble(textFields.get(4).getText());
                
                
                double perimeter = sideA + sideB + baseC + baseD;
                double area = ((baseC + baseD) / 2 )* height;

                lblAnswer.setText("<html>Perimeter = " + decimalFormat.format(perimeter) +
                "<br>Area = " + decimalFormat.format(area) + "</html>");
            } catch (NumberFormatException ex) {
                lblAnswer.setText("Invalid radius. Please enter a number.");
            } 
        }        
        

    }//GEN-LAST:event_btnCalculateActionPerformed

    private void btnClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearActionPerformed
        // TODO add your handling code here:
        textFieldsHandler();
        lblAnswer.setText("Selected Shape Answer");
    }//GEN-LAST:event_btnClearActionPerformed





    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Main().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCalculate;
    private javax.swing.JButton btnCircle;
    private javax.swing.JButton btnClear;
    private javax.swing.JButton btnDecagon;
    private javax.swing.JButton btnEllipse;
    private javax.swing.JButton btnHeptagon;
    private javax.swing.JButton btnHexagon;
    private javax.swing.JButton btnNonagon;
    private javax.swing.JButton btnOctagon;
    private javax.swing.JButton btnParallelogram;
    private javax.swing.JButton btnPentagon;
    private javax.swing.JButton btnRectangle;
    private javax.swing.JButton btnRhombus;
    private javax.swing.JButton btnSquare;
    private javax.swing.JButton btnTrapezoid;
    private javax.swing.JButton btnTriangle;
    private javax.swing.JLabel lblAnswer;
    private javax.swing.JLabel lblSelectedShapeFormula;
    private javax.swing.JLabel lblSelectedShapeName;
    private javax.swing.JPanel mainPanel;
    private javax.swing.JPanel panel2dShapes;
    private javax.swing.JPanel panel3dShapes;
    private javax.swing.JPanel panelSelectedShapeAnswer;
    private javax.swing.JPanel panelSelectedShapeFormula;
    private javax.swing.JPanel panelSelectedShapeInputs;
    private javax.swing.JPanel panelShapeDiagram;
    private javax.swing.JPanel panelShapeName;
    private javax.swing.JPanel panelTextFields;
    private javax.swing.JPanel panelTitle;
    private javax.swing.JScrollPane scrollPane2dShapes;
    private javax.swing.JScrollPane scrollPane3dShapes;
    private javax.swing.JTabbedPane tabbedPaneShapeSelection;
    // End of variables declaration//GEN-END:variables
}
