/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package finalnatalagathisasin;

import java.awt.Font;
import java.awt.GridLayout;
import java.text.DecimalFormat;
import javax.swing.JLabel;
import javax.swing.JTextField;
import java.util.List;
import java.util.ArrayList;

/**
 *
 * @author rexiepimentelMBP
 */
public class Main extends javax.swing.JFrame {

    /**
     * Creates new form Main
     */
    private List<JTextField> textFields = new ArrayList<>();
    int givenFields;
    private List<String> variableNames = new ArrayList<>();
    
    
    Font defaultFont = new Font("Helvetica Neue", Font.PLAIN, 36);
    DecimalFormat decimalFormat = new DecimalFormat("#.00");
    
    ShapesFormula sf = new ShapesFormula();
    
    public Main() {
        initComponents();
        
    }
    public void textFieldsHandler(){
        
        panelTextFields.removeAll();
        panelTextFields.setLayout(new GridLayout(0, 2));
        textFields.clear();
        
        
        int count;
        int givenFieldCount = givenFields;

        for (int i = 0; i < givenFieldCount; i++) {
            String varNames = variableNames.get(i);
            
            JLabel label = new JLabel(varNames + ": ");
            label.setFont(defaultFont);
            panelTextFields.add(label);
            
            JTextField field  = new JTextField(10);
            field.setFont(defaultFont);
            panelTextFields.add(field);
            textFields.add(field);
        }

        panelTextFields.revalidate();
        panelTextFields.repaint();
    }
    
    public void clearAnswer(){
        lblAnswer.setText("Selected Shape Answer");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainPanel = new javax.swing.JPanel();
        panelTitle = new javax.swing.JPanel();
        panelShapeName = new javax.swing.JPanel();
        lblSelectedShapeName = new javax.swing.JLabel();
        panelSelectedShapeFormula = new javax.swing.JPanel();
        lblSelectedShapeFormula = new javax.swing.JLabel();
        panelShapeDiagram = new javax.swing.JPanel();
        panelSelectedShapeAnswer = new javax.swing.JPanel();
        lblAnswer = new javax.swing.JLabel();
        panelSelectedShapeInputs = new javax.swing.JPanel();
        panelTextFields = new javax.swing.JPanel();
        btnCalculate = new javax.swing.JButton();
        btnClear = new javax.swing.JButton();
        tabbedPaneShapeSelection = new javax.swing.JTabbedPane();
        jScrollPane3 = new javax.swing.JScrollPane();
        jPanel3 = new javax.swing.JPanel();
        btnCircle = new javax.swing.JButton();
        btnEllipse = new javax.swing.JButton();
        btnTriangle = new javax.swing.JButton();
        btnRectangle = new javax.swing.JButton();
        btnSquare = new javax.swing.JButton();
        btnRectangle1 = new javax.swing.JButton();
        jScrollPane4 = new javax.swing.JScrollPane();
        jPanel4 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        mainPanel.setLayout(null);

        panelTitle.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        javax.swing.GroupLayout panelTitleLayout = new javax.swing.GroupLayout(panelTitle);
        panelTitle.setLayout(panelTitleLayout);
        panelTitleLayout.setHorizontalGroup(
            panelTitleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 218, Short.MAX_VALUE)
        );
        panelTitleLayout.setVerticalGroup(
            panelTitleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 148, Short.MAX_VALUE)
        );

        mainPanel.add(panelTitle);
        panelTitle.setBounds(0, 0, 220, 150);

        panelShapeName.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        panelShapeName.setLayout(null);

        lblSelectedShapeName.setFont(new java.awt.Font("Helvetica Neue", 0, 24)); // NOI18N
        lblSelectedShapeName.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblSelectedShapeName.setText("Selected Shape Name");
        panelShapeName.add(lblSelectedShapeName);
        lblSelectedShapeName.setBounds(6, 21, 1048, 29);

        mainPanel.add(panelShapeName);
        panelShapeName.setBounds(220, 0, 1060, 60);

        panelSelectedShapeFormula.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        panelSelectedShapeFormula.setLayout(null);

        lblSelectedShapeFormula.setFont(new java.awt.Font("Helvetica Neue", 0, 24)); // NOI18N
        lblSelectedShapeFormula.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblSelectedShapeFormula.setText("Selected Shape Formula");
        panelSelectedShapeFormula.add(lblSelectedShapeFormula);
        lblSelectedShapeFormula.setBounds(0, -1, 1060, 110);

        mainPanel.add(panelSelectedShapeFormula);
        panelSelectedShapeFormula.setBounds(220, 610, 1060, 110);

        panelShapeDiagram.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        javax.swing.GroupLayout panelShapeDiagramLayout = new javax.swing.GroupLayout(panelShapeDiagram);
        panelShapeDiagram.setLayout(panelShapeDiagramLayout);
        panelShapeDiagramLayout.setHorizontalGroup(
            panelShapeDiagramLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 288, Short.MAX_VALUE)
        );
        panelShapeDiagramLayout.setVerticalGroup(
            panelShapeDiagramLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 548, Short.MAX_VALUE)
        );

        mainPanel.add(panelShapeDiagram);
        panelShapeDiagram.setBounds(220, 60, 290, 550);

        panelSelectedShapeAnswer.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        lblAnswer.setFont(new java.awt.Font("Helvetica Neue", 0, 24)); // NOI18N
        lblAnswer.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblAnswer.setText("Selected Shape Answer");

        javax.swing.GroupLayout panelSelectedShapeAnswerLayout = new javax.swing.GroupLayout(panelSelectedShapeAnswer);
        panelSelectedShapeAnswer.setLayout(panelSelectedShapeAnswerLayout);
        panelSelectedShapeAnswerLayout.setHorizontalGroup(
            panelSelectedShapeAnswerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelSelectedShapeAnswerLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblAnswer, javax.swing.GroupLayout.DEFAULT_SIZE, 756, Short.MAX_VALUE)
                .addContainerGap())
        );
        panelSelectedShapeAnswerLayout.setVerticalGroup(
            panelSelectedShapeAnswerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelSelectedShapeAnswerLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblAnswer, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        mainPanel.add(panelSelectedShapeAnswer);
        panelSelectedShapeAnswer.setBounds(510, 350, 770, 260);

        panelSelectedShapeInputs.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        panelTextFields.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        panelTextFields.setLayout(new java.awt.GridLayout(1, 0));

        btnCalculate.setText("Calculate");
        btnCalculate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCalculateActionPerformed(evt);
            }
        });

        btnClear.setText("Clear");
        btnClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClearActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelSelectedShapeInputsLayout = new javax.swing.GroupLayout(panelSelectedShapeInputs);
        panelSelectedShapeInputs.setLayout(panelSelectedShapeInputsLayout);
        panelSelectedShapeInputsLayout.setHorizontalGroup(
            panelSelectedShapeInputsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelSelectedShapeInputsLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelTextFields, javax.swing.GroupLayout.PREFERRED_SIZE, 567, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelSelectedShapeInputsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnCalculate, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnClear, javax.swing.GroupLayout.DEFAULT_SIZE, 177, Short.MAX_VALUE))
                .addContainerGap())
        );
        panelSelectedShapeInputsLayout.setVerticalGroup(
            panelSelectedShapeInputsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelSelectedShapeInputsLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(panelSelectedShapeInputsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelSelectedShapeInputsLayout.createSequentialGroup()
                        .addComponent(btnCalculate, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnClear, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(panelTextFields, javax.swing.GroupLayout.PREFERRED_SIZE, 258, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(15, Short.MAX_VALUE))
        );

        mainPanel.add(panelSelectedShapeInputs);
        panelSelectedShapeInputs.setBounds(510, 60, 770, 290);

        btnCircle.setText("Circle");
        btnCircle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCircleActionPerformed(evt);
            }
        });

        btnEllipse.setText("Ellipse");
        btnEllipse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEllipseActionPerformed(evt);
            }
        });

        btnTriangle.setText("Triangle");
        btnTriangle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTriangleActionPerformed(evt);
            }
        });

        btnRectangle.setText("Rectangle");
        btnRectangle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRectangleActionPerformed(evt);
            }
        });

        btnSquare.setText("Square");
        btnSquare.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSquareActionPerformed(evt);
            }
        });

        btnRectangle1.setText("Rectangle");
        btnRectangle1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRectangle1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(btnCircle, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnEllipse, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnTriangle, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnRectangle, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnSquare, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnRectangle1, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnCircle, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnEllipse, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnTriangle, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnSquare, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnRectangle, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnRectangle1, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(134, Short.MAX_VALUE))
        );

        jScrollPane3.setViewportView(jPanel3);

        tabbedPaneShapeSelection.addTab("2D Shapes", jScrollPane3);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 214, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 529, Short.MAX_VALUE)
        );

        jScrollPane4.setViewportView(jPanel4);

        tabbedPaneShapeSelection.addTab("3D Shapes", jScrollPane4);

        mainPanel.add(tabbedPaneShapeSelection);
        tabbedPaneShapeSelection.setBounds(0, 150, 220, 570);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 1280, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 720, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCircleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCircleActionPerformed
        // TODO add your handling code here:

        givenFields = 1;
        
        lblSelectedShapeName.setText("Circle");
        lblSelectedShapeFormula.setText(sf.circle());
        
        variableNames.clear();
        variableNames.add("radius");
        
        
        textFieldsHandler();
        clearAnswer();
        
    }//GEN-LAST:event_btnCircleActionPerformed

    private void btnEllipseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEllipseActionPerformed
        // TODO add your handling code here:
        
        givenFields = 2;
        
        lblSelectedShapeName.setText("Ellipse");
        lblSelectedShapeFormula.setText(sf.circle());
        
        variableNames.clear();
        variableNames.add("Given a");
        variableNames.add("Given b");
        
        textFieldsHandler();
        clearAnswer();
    }//GEN-LAST:event_btnEllipseActionPerformed

    private void btnTriangleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTriangleActionPerformed
        // TODO add your handling code here:
        
        givenFields = 3;
        
        lblSelectedShapeName.setText("Triangle");
        lblSelectedShapeFormula.setText(sf.triangle());
        
        variableNames.clear();
        variableNames.add("Given a");
        variableNames.add("Given b");
        variableNames.add("Given c");
        
        textFieldsHandler();
        clearAnswer();
    }//GEN-LAST:event_btnTriangleActionPerformed

    private void btnRectangleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRectangleActionPerformed
        // TODO add your handling code here:

        givenFields = 2;
        
        lblSelectedShapeName.setText("Rectangle");
        lblSelectedShapeFormula.setText(sf.rectangle());
        
        variableNames.clear();
        variableNames.add("Given length");
        variableNames.add("Given width");
        
        textFieldsHandler();
        clearAnswer();
    }//GEN-LAST:event_btnRectangleActionPerformed

    private void btnSquareActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSquareActionPerformed
        // TODO add your handling code here:

        givenFields = 1;
        
        lblSelectedShapeName.setText("Square");
        lblSelectedShapeFormula.setText(sf.square());
        
        variableNames.clear();
        variableNames.add("Given a");
        
        textFieldsHandler();
        clearAnswer();
    }//GEN-LAST:event_btnSquareActionPerformed

    private void btnRectangle1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRectangle1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnRectangle1ActionPerformed

    private void btnCalculateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCalculateActionPerformed
        // TODO add your handling code here:
        if ("Circle".equals(lblSelectedShapeName.getText())) {
            try {
                //For Rounding: https://stackoverflow.com/questions/2808535/round-a-double-to-2-decimal-places
                //For Double Handler: https://stackoverflow.com/questions/49466030/how-to-convert-double-values-to-string-in-a-text-field
                double radius = Double.parseDouble(textFields.get(0).getText());
                double diameter = radius * 2;
                double circumference = 2 * Math.PI * radius;
                double area = Math.PI * radius * radius;

                lblAnswer.setText("<html>Diameter = " + decimalFormat.format(diameter) +
                    "<br>Circumference = " + decimalFormat.format(circumference) +
                    "<br>Area = " + decimalFormat.format(area) + "</html>");
                } catch (NumberFormatException ex) {
                lblAnswer.setText("Invalid radius. Please enter a number.");
                }
            
        } else if ("Ellipse".equals(lblSelectedShapeName.getText())) {
            try {
                double a = Double.parseDouble(textFields.get(0).getText());
                double b = Double.parseDouble(textFields.get(1).getText());
                double area = Math.PI * a * b;
                double perimeter = 2 * Math.PI * Math.sqrt((a * a + b * b) / 2);

                lblAnswer.setText("<html>Perimeter = " + decimalFormat.format(perimeter) +
                "<br>Area = " + decimalFormat.format(area) + "</html>");
            } catch (NumberFormatException ex) {
                lblAnswer.setText("Invalid radius. Please enter a number.");
            }
        } else if ("Triangle".equals(lblSelectedShapeName.getText())) {
            try {
                double a = Double.parseDouble(textFields.get(0).getText());
                double b = Double.parseDouble(textFields.get(1).getText());
                double c = Double.parseDouble(textFields.get(2).getText());
                
                double s = (a + b + c) / 2;
                double perimeter = a + b + c;
                double area = Math.sqrt(s * (s - a) * (s - b) * (s - c));

                lblAnswer.setText("<html>Perimeter = " + decimalFormat.format(perimeter) +
                "<br>Area = " + decimalFormat.format(area) + "</html>");
            } catch (NumberFormatException ex) {
                lblAnswer.setText("Invalid radius. Please enter a number.");
            }            
        } else if ("Square".equals(lblSelectedShapeName.getText())) {
            try {
                double a = Double.parseDouble(textFields.get(0).getText());
                
                double perimeter = 4 * a;
                double area = Math.pow(a, 2);

                lblAnswer.setText("<html>Perimeter = " + decimalFormat.format(perimeter) +
                "<br>Area = " + decimalFormat.format(area) + "</html>");
            } catch (NumberFormatException ex) {
                lblAnswer.setText("Invalid radius. Please enter a number.");
            }
        } else if ("Rectangle".equals(lblSelectedShapeName.getText())) {
            try {
                double length = Double.parseDouble(textFields.get(0).getText());
                double width = Double.parseDouble(textFields.get(1).getText());
                
                double perimeter = 2 * (length + width);
                double area = length * width;

                lblAnswer.setText("<html>Perimeter = " + decimalFormat.format(perimeter) +
                "<br>Area = " + decimalFormat.format(area) + "</html>");
            } catch (NumberFormatException ex) {
                lblAnswer.setText("Invalid radius. Please enter a number.");
            }
        }

    }//GEN-LAST:event_btnCalculateActionPerformed

    private void btnClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearActionPerformed
        // TODO add your handling code here:
        textFieldsHandler();
        lblAnswer.setText("Selected Shape Answer");
    }//GEN-LAST:event_btnClearActionPerformed


    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Main().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCalculate;
    private javax.swing.JButton btnCircle;
    private javax.swing.JButton btnClear;
    private javax.swing.JButton btnEllipse;
    private javax.swing.JButton btnRectangle;
    private javax.swing.JButton btnRectangle1;
    private javax.swing.JButton btnSquare;
    private javax.swing.JButton btnTriangle;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JLabel lblAnswer;
    private javax.swing.JLabel lblSelectedShapeFormula;
    private javax.swing.JLabel lblSelectedShapeName;
    private javax.swing.JPanel mainPanel;
    private javax.swing.JPanel panelSelectedShapeAnswer;
    private javax.swing.JPanel panelSelectedShapeFormula;
    private javax.swing.JPanel panelSelectedShapeInputs;
    private javax.swing.JPanel panelShapeDiagram;
    private javax.swing.JPanel panelShapeName;
    private javax.swing.JPanel panelTextFields;
    private javax.swing.JPanel panelTitle;
    private javax.swing.JTabbedPane tabbedPaneShapeSelection;
    // End of variables declaration//GEN-END:variables
}
